const mongoose = require('mongoose');

const contractSchema = new mongoose.Schema({
  // Contract identification
  contractNumber: {
    type: String,
    unique: true
    // Removed required: true since this is auto-generated by pre-save hook
  },
  
  // Relations
  tenantId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  reservation: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Reservation',
    required: true
  },
  
  // Customer information (Zákazník)
  customer: {
    firstName: {
      type: String,
      required: true
    },
    lastName: {
      type: String,
      required: true
    },
    phone: {
      type: String,
      required: true
    },
    email: {
      type: String,
      required: true
    },
    address: {
      street: String,
      city: String,
      state: String,
      zipCode: String,
      country: String
    },
    idNumber: {
      type: String, // Číslo OP (ID card number)
      sparse: true
    },
    licenseNumber: {
      type: String, // Číslo vodičského preukazu
      sparse: true
    }
  },

  // Vehicle information (Vozidlo)
  vehicle: {
    brand: {
      type: String,
      required: true
    },
    model: {
      type: String,
      required: true
    },
    year: Number,
    registrationNumber: {
      type: String,
      required: true
    },
    vin: String,
    category: String,
    fuelType: String,
    transmission: String,
    color: String // Farba vozidla
  },
  
  // Rental details (Prenájom)
  rental: {
    startDate: {
      type: Date,
      required: true
    },
    endDate: {
      type: Date,
      required: true
    },
    pickupLocation: {
      type: String,
      required: true
    },
    returnLocation: {
      type: String,
      required: true
    },
    totalDays: {
      type: Number,
      required: true
    },
    dailyRate: {
      type: Number,
      required: true
    },
    totalAmount: {
      type: Number,
      required: true
    }
  },
  
  // Additional services (Doplnkové služby)
  additionalServices: [{
    name: {
      type: String,
      required: true
    },
    price: {
      type: Number,
      required: true
    },
    quantity: {
      type: Number,
      default: 1
    }
  }],
  
  // Special services
  specialServices: {
    delivery: {
      isSelected: {
        type: Boolean,
        default: false
      },
      price: {
        type: Number,
        default: 0
      },
      address: String
    },
    afterHours: {
      isSelected: {
        type: Boolean,
        default: false
      },
      price: {
        type: Number,
        default: 0
      },
      notes: String
    }
  },
  
  // Rental rules (Pravidlá prenájmu) - Static
  rentalRules: {
    dailyKmLimit: {
      type: Number,
      default: 200
    },
    excessKmFee: {
      type: Number,
      default: 0.25 // EUR per km
    },
    insuranceDeductible: {
      type: Number,
      default: 1000 // EUR
    },
    prohibitedActivities: [{
      type: String,
      default: ['Fajčenie vo vozidle', 'Prevoz domácich zvierat bez schválenia', 'Jazda v teréne', 'Používanie vozidla na komerčné účely']
    }],
    cancellationPolicy: {
      type: String,
      default: 'Zrušenie rezervácie je možné do 24 hodín pred začiatkom prenájmu bez poplatku. Pri zrušení menej ako 24 hodín pred začiatkom sa účtuje poplatok 50% z celkovej sumy.'
    }
  },
  
  // Contract status
  status: {
    type: String,
    enum: ['draft', 'pending', 'signed', 'cancelled', 'expired'],
    default: 'draft'
  },
  
  // Signatures
  signatures: {
    customer: {
      signed: {
        type: Boolean,
        default: false
      },
      signedAt: Date,
      signatureData: String, // Base64 encoded signature
      ipAddress: String
    },
    staff: {
      signed: {
        type: Boolean,
        default: false
      },
      signedAt: Date,
      signedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
      }
    }
  },
  
  // Metadata
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  lastModifiedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  
  // Version control
  version: {
    type: Number,
    default: 1
  },
  
  // PDF generation
  pdfGenerated: {
    type: Boolean,
    default: false
  },
  pdfUrl: String,

  // Notes
  notes: String,

  // ============ NitraCar-specific fields ============

  // Payment method
  paymentMethod: {
    type: String,
    enum: ['hotovost', 'karta', 'faktura', 'prevod', 'stripe'],
    default: 'hotovost'
  },

  // Deposit amount
  deposit: {
    type: Number,
    default: 0
  },

  // Customer additional identification (NitraCar)
  customerIdentification: {
    idCardNumber: String,      // Cislo obcianskeho preukazu
    passportNumber: String,    // Cislo pasu
    driverLicenseNumber: String // Cislo vodicskeho preukazu
  },

  // Handover protocol - when vehicle is picked up by customer
  handover: {
    registrationCard: {
      type: Boolean,
      default: false // Osvedcenie o evidencii, biela karta
    },
    mandatoryEquipment: {
      type: Boolean,
      default: false // Povinna vybava, rezerva
    },
    damages: {
      type: String,
      default: '' // Popis poskodeni alebo 'Bez poskodenia'
    },
    fuelLevel: {
      type: String,
      enum: ['empty', 'quarter', 'third', 'half', 'three-quarters', 'full'],
      default: 'full' // Stav PHM v nadrzi
    },
    depositPaid: {
      type: Number,
      default: 0 // Depozit uhradeny (200, 500, 1000 EUR)
    },
    mileage: {
      type: Number,
      default: 0 // Stav pocitadla v km
    },
    handoverDate: Date,
    handoverByStaff: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    customerSignature: String, // Base64 encoded signature
    staffSignature: String     // Base64 encoded signature
  },

  // Return protocol - when vehicle is returned by customer
  return: {
    registrationCard: {
      type: Boolean,
      default: false // Osvedcenie o evidencii, biela karta
    },
    mandatoryEquipment: {
      type: Boolean,
      default: false // Povinna vybava
    },
    damages: {
      type: String,
      default: '' // Popis poskodeni alebo 'Bez poskodenia'
    },
    fuelLevel: {
      type: String,
      enum: ['empty', 'quarter', 'third', 'half', 'three-quarters', 'full'],
      default: 'full' // Stav PHM v nadrzi
    },
    depositReturned: {
      type: Number,
      default: 0 // Depozit vrateny (200, 500, 1000 EUR)
    },
    mileage: {
      type: Number,
      default: 0 // Stav pocitadla v km
    },
    returnDate: Date,
    returnByStaff: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    customerSignature: String, // Base64 encoded signature
    staffSignature: String     // Base64 encoded signature
  }
}, {
  timestamps: true
});

// Indexes for better performance
contractSchema.index({ tenantId: 1, contractNumber: 1 }, { unique: true });
contractSchema.index({ tenantId: 1, reservation: 1 });
contractSchema.index({ tenantId: 1, status: 1 });
contractSchema.index({ tenantId: 1, createdAt: 1 });

// Generate contract number with the format: YYYYMMDD##N
contractSchema.pre('save', async function(next) {
  if (this.isNew && !this.contractNumber) {
    try {
      console.log('🔖 [CONTRACT] Generating contract number for new contract...');
      
      const today = new Date();
      const year = today.getFullYear();
      const month = String(today.getMonth() + 1).padStart(2, '0');
      const day = String(today.getDate()).padStart(2, '0');
      
      // Format: YYYYMMDD
      const datePrefix = `${year}${month}${day}`;
      console.log('🔖 [CONTRACT] Date prefix:', datePrefix);
      
      // Find contracts created today for this tenant
      const startOfDay = new Date(today);
      startOfDay.setHours(0, 0, 0, 0);
      
      const endOfDay = new Date(today);
      endOfDay.setHours(23, 59, 59, 999);
      
      let todayContractsCount = 0;
      try {
        todayContractsCount = await this.constructor.countDocuments({
          tenantId: this.tenantId,
          createdAt: {
            $gte: startOfDay,
            $lte: endOfDay
          }
        });
        console.log('🔖 [CONTRACT] Today contracts count:', todayContractsCount);
      } catch (countError) {
        console.error('🔖 [CONTRACT] Error counting today contracts, using fallback:', countError);
        // Use current timestamp as fallback to ensure uniqueness
        todayContractsCount = Date.now() % 100;
      }
      
      // Sequential number with zero padding (01, 02, 03, etc.)
      const sequentialNumber = String(todayContractsCount + 1).padStart(2, '0');
      
      // Final format: YYYYMMDD##N (e.g., 2025062201N)
      this.contractNumber = `${datePrefix}${sequentialNumber}N`;
      
      console.log('🔖 [CONTRACT] Generated contract number:', this.contractNumber);
    } catch (error) {
      console.error('🔖 [CONTRACT] Error generating contract number:', error);
      // Generate a more robust fallback contract number
      const timestamp = Date.now();
      const randomSuffix = Math.random().toString(36).substring(2, 5).toUpperCase();
      this.contractNumber = `${timestamp}${randomSuffix}N`;
      console.log('🔖 [CONTRACT] Using fallback contract number:', this.contractNumber);
    }
  }
  
  // Ensure contract number is always set before saving
  if (!this.contractNumber) {
    const timestamp = Date.now();
    const randomSuffix = Math.random().toString(36).substring(2, 5).toUpperCase();
    this.contractNumber = `EMERGENCY${timestamp}${randomSuffix}N`;
    console.log('🔖 [CONTRACT] Emergency contract number generated:', this.contractNumber);
  }
  
  next();
});

// Virtual for full customer name
contractSchema.virtual('customerFullName').get(function() {
  return `${this.customer.firstName} ${this.customer.lastName}`;
});

// Virtual for vehicle full name
contractSchema.virtual('vehicleFullName').get(function() {
  return `${this.vehicle.brand} ${this.vehicle.model}`;
});

// Virtual for contract duration
contractSchema.virtual('duration').get(function() {
  return this.rental.totalDays;
});

// Method to calculate total additional services cost
contractSchema.methods.calculateAdditionalServicesCost = function() {
  let total = 0;
  
  // Regular additional services
  this.additionalServices.forEach(service => {
    total += service.price * service.quantity;
  });
  
  // Special services
  if (this.specialServices.delivery.isSelected) {
    total += this.specialServices.delivery.price;
  }
  
  if (this.specialServices.afterHours.isSelected) {
    total += this.specialServices.afterHours.price;
  }
  
  return total;
};

// Method to calculate total contract amount
contractSchema.methods.calculateTotalAmount = function() {
  const rentalTotal = this.rental.totalAmount;
  const additionalServicesTotal = this.calculateAdditionalServicesCost();
  return rentalTotal + additionalServicesTotal;
};

// Method to check if contract is fully signed
contractSchema.methods.isFullySigned = function() {
  return this.signatures.customer.signed && this.signatures.staff.signed;
};

// Method to check if contract can be modified
contractSchema.methods.canBeModified = function() {
  return ['draft', 'pending'].includes(this.status) && !this.isFullySigned();
};

// Static method to create contract from reservation
contractSchema.statics.createFromReservation = async function(reservationId, tenantId, createdBy) {
  const Reservation = require('./Reservation');
  const Car = require('./Car');
  const User = require('./User');
  
  console.log('🔖 [CONTRACT MODEL] Creating contract from reservation:', reservationId);
  console.log('🔖 [CONTRACT MODEL] Tenant ID:', tenantId);
  console.log('🔖 [CONTRACT MODEL] Created by:', createdBy);
  
  const reservation = await Reservation.findById(reservationId)
    .populate('customer', 'firstName lastName email phone address idNumber licenseNumber licenseExpiry dateOfBirth')
    .populate('car', 'brand model year registrationNumber vin category fuelType transmission color mileage');
  
  if (!reservation) {
    throw new Error('Reservation not found');
  }
  
  console.log('🔖 [CONTRACT MODEL] Reservation found:', reservation._id);
  console.log('🔖 [CONTRACT MODEL] Reservation data:', JSON.stringify(reservation.toObject(), null, 2));
  
  if (!reservation.customer) {
    throw new Error('Reservation customer not found');
  }
  
  console.log('🔖 [CONTRACT MODEL] Customer data:', JSON.stringify(reservation.customer.toObject(), null, 2));
  
  if (!reservation.car) {
    throw new Error('Reservation car not found');
  }
  
  console.log('🔖 [CONTRACT MODEL] Car data:', JSON.stringify(reservation.car.toObject(), null, 2));
  
  // Calculate days for the rental
  const days = Math.ceil((new Date(reservation.endDate) - new Date(reservation.startDate)) / (1000 * 60 * 60 * 24));
  console.log('🔖 [CONTRACT MODEL] Calculated days:', days);
  
  // Format customer address for Slovak format
  const formatSlovakAddress = (address) => {
    if (!address) {
      return {
        street: '',
        city: '',
        state: '',
        zipCode: '',
        country: 'Slovensko'
      };
    }
    
    return {
      street: address.street || '',
      city: address.city || '',
      state: address.state || '',
      zipCode: address.zipCode || '',
      country: address.country || 'Slovensko'
    };
  };
  
  const contractData = {
    tenantId,
    reservation: reservationId,
    customer: {
      firstName: reservation.customer.firstName || 'Neuvedené',
      lastName: reservation.customer.lastName || 'Neuvedené',
      phone: reservation.customer.phone || 'Neuvedené',
      email: reservation.customer.email || 'neuvedene@email.sk',
      address: formatSlovakAddress(reservation.customer.address),
      idNumber: reservation.customer.idNumber || 'Neuvedené',
      licenseNumber: reservation.customer.licenseNumber || 'Neuvedené'
    },
    vehicle: {
      brand: reservation.car.brand || 'Neuvedené',
      model: reservation.car.model || 'Neuvedené',
      year: reservation.car.year || new Date().getFullYear(),
      registrationNumber: reservation.car.registrationNumber || 'Neuvedené',
      vin: reservation.car.vin || 'Neuvedené',
      category: reservation.car.category || 'economy',
      fuelType: reservation.car.fuelType || 'benzín',
      transmission: reservation.car.transmission || 'manuálna',
      color: reservation.car.color || 'Neuvedená'
    },
    rental: {
      startDate: reservation.startDate,
      endDate: reservation.endDate,
      pickupLocation: reservation.pickupLocation?.name || 'Neuvedené',
      returnLocation: reservation.dropoffLocation?.name || 'Neuvedené',
      totalDays: days,
      dailyRate: reservation.pricing?.dailyRate || 0,
      totalAmount: reservation.pricing?.totalAmount || 0
    },
    additionalServices: [], // Will be populated from reservation if needed
    createdBy,
    // NitraCar-specific fields
    paymentMethod: reservation.paymentType || 'hotovost',
    deposit: reservation.pricing?.deposit || 0,
    customerIdentification: {
      idCardNumber: reservation.customer.idNumber || '',
      driverLicenseNumber: reservation.customer.licenseNumber || ''
    },
    // Initialize handover with car's current mileage
    handover: {
      mileage: reservation.car.mileage?.current || 0,
      depositPaid: reservation.pricing?.deposit || 0
    }
  };
  
  console.log('🔖 [CONTRACT MODEL] Contract data prepared:', JSON.stringify(contractData, null, 2));
  console.log('🔖 [CONTRACT MODEL] ✅ Customer (zákazník) successfully mapped from reservation');
  
  const contract = new this(contractData);
  await contract.save();
  
  console.log('🔖 [CONTRACT MODEL] ✅ Contract saved to database with ID:', contract._id);
  
  return contract;
};

module.exports = mongoose.model('Contract', contractSchema); 
